# **Practical No. 4: Elementary transformation**

>  **Laboratory Learning Outcome (LLO) 4.1:** Calculate the rank of a matrix by elementary transformation using Python programming.

>  **Course Outcome (CO):** CO2

>  **Title:** Write a program to find a) Elementary row and column transformations using Python loops. b) Rank of a matrix.

> **Domain:** Machine Learning
 <br> **Subject:** Mathematics for Machine Learning
 <br> **Language:** Python

> **Description:** a) Elementary row and column transformations using Python loops: This involves performing basic matrix operations such as row swapping, row scaling, and row addition using Python loops. These transformations help simplify matrices for further analysis. They are commonly used in solving linear equations and matrix reduction.
b) Rank of a matrix: The rank of a matrix is the number of linearly independent rows or columns it contains. It indicates whether a system of equations has a unique solution, infinite solutions, or no solution. Rank is often determined using row-reduction techniques.

> **Resource:**
  
---
<center> </center>


In [1]:
# -------------------------------------------------------
#  PART (A): Elementary Row and Column Transformations
# -------------------------------------------------------

def print_matrix(M):
    for row in M:
        print(row)
    print()

# Swap two rows
def row_swap(M, i, j):
    M[i], M[j] = M[j], M[i]

# Multiply row by a constant
def row_multiply(M, i, k):
    M[i] = [k * x for x in M[i]]

# Row replacement: Ri = Ri + k * Rj
def row_replace(M, i, j, k):
    M[i] = [x + k * y for x, y in zip(M[i], M[j])]

# Swap two columns
def col_swap(M, i, j):
    for row in M:
        row[i], row[j] = row[j], row[i]

# Multiply column by constant
def col_multiply(M, i, k):
    for row in M:
        row[i] *= k

# Column replacement: Ci = Ci + k * Cj
def col_replace(M, i, j, k):
    for row in M:
        row[i] += k * row[j]


# Example matrix
A = [
    [2, 1, -1],
    [4, 1, 0],
    [6, 0, 1]
]

print("Original Matrix:")
print_matrix(A)

# Perform row and column operations
row_swap(A, 0, 1)
print("After Row Swap R1 <-> R2:")
print_matrix(A)

row_multiply(A, 0, 3)
print("After Row Multiply R1 = 3 * R1:")
print_matrix(A)

row_replace(A, 2, 0, -1)
print("After Row Replace R3 = R3 - R1:")
print_matrix(A)

col_swap(A, 0, 2)
print("After Column Swap C1 <-> C3:")
print_matrix(A)

# -------------------------------------------------------
#  PART (B): Compute Rank of Matrix (Gauss elimination)
# -------------------------------------------------------

def matrix_rank(M):
    M = [row[:] for row in M]  # make a copy
    rows = len(M)
    cols = len(M[0])
    rank = 0

    for col in range(cols):
        pivot = None
        # Find pivot row
        for row in range(rank, rows):
            if M[row][col] != 0:
                pivot = row
                break

        if pivot is None:
            continue

        # Swap to make pivot in correct row
        M[rank], M[pivot] = M[pivot], M[rank]

        pivot_value = M[rank][col]

        # Normalize pivot row
        for j in range(col, cols):
            M[rank][j] /= pivot_value

        # Eliminate below
        for r in range(rank + 1, rows):
            factor = M[r][col]
            for c in range(col, cols):
                M[r][c] -= factor * M[rank][c]

        rank += 1

    return rank

# Example matrix to compute rank
B = [
    [2, 1, -1],
    [4, 2, -2],
    [6, 3, -3]
]

print("Matrix For Rank Calculation:")
print_matrix(B)

print("Rank of the matrix:", matrix_rank(B))

Original Matrix:
[2, 1, -1]
[4, 1, 0]
[6, 0, 1]

After Row Swap R1 <-> R2:
[4, 1, 0]
[2, 1, -1]
[6, 0, 1]

After Row Multiply R1 = 3 * R1:
[12, 3, 0]
[2, 1, -1]
[6, 0, 1]

After Row Replace R3 = R3 - R1:
[12, 3, 0]
[2, 1, -1]
[-6, -3, 1]

After Column Swap C1 <-> C3:
[0, 3, 12]
[-1, 1, 2]
[1, -3, -6]

Matrix For Rank Calculation:
[2, 1, -1]
[4, 2, -2]
[6, 3, -3]

Rank of the matrix: 1


In [3]:
import numpy as np

def print_matrix(M):
    print(M, "\n")

# ---------- PART (A): Row & Column Transformations ----------

A = np.array([
    [2, 1, -1],
    [4, 1,  0],
    [6, 0,  1]
], dtype=float)

print("Original Matrix:")
print_matrix(A)

# Row swap R1 <-> R2
A[[0, 1]] = A[[1, 0]]
print("After Row Swap R1 <-> R2:")
print_matrix(A)

# Row multiply R1 = 3 * R1
A[0] *= 3
print("After Row Multiply R1 = 3 * R1:")
print_matrix(A)

# Row replace R3 = R3 - R1
A[2] = A[2] - A[0]
print("After Row Replace R3 = R3 - R1:")
print_matrix(A)

# Column swap C1 <-> C3
A[:, [0, 2]] = A[:, [2, 0]]
print("After Column Swap C1 <-> C3:")
print_matrix(A)

# ---------- PART (B): Rank of Matrix ----------

B = np.array([
    [2, 1, -1],
    [4, 2, -2],
    [6, 3, -3]
], dtype=float)

print("Matrix For Rank Calculation:")
print_matrix(B)

print("Rank of the matrix:", np.linalg.matrix_rank(B))


Original Matrix:
[[ 2.  1. -1.]
 [ 4.  1.  0.]
 [ 6.  0.  1.]] 

After Row Swap R1 <-> R2:
[[ 4.  1.  0.]
 [ 2.  1. -1.]
 [ 6.  0.  1.]] 

After Row Multiply R1 = 3 * R1:
[[12.  3.  0.]
 [ 2.  1. -1.]
 [ 6.  0.  1.]] 

After Row Replace R3 = R3 - R1:
[[12.  3.  0.]
 [ 2.  1. -1.]
 [-6. -3.  1.]] 

After Column Swap C1 <-> C3:
[[ 0.  3. 12.]
 [-1.  1.  2.]
 [ 1. -3. -6.]] 

Matrix For Rank Calculation:
[[ 2.  1. -1.]
 [ 4.  2. -2.]
 [ 6.  3. -3.]] 

Rank of the matrix: 1
