# **Practical No. 8: Eigen values and vector Mx3**

>  **Laboratory Learning Outcome (LLO) 8.1:** LLO 8.1 Calculate eigen-values and eigen-vectors for the given matrix of order 3 using Python programming.

>  **Course Outcome (CO):** CO2

>  **Title:** Write a program to calculate eigen values and eigen vector for given matrix of order 3.

> **Domain:** Machine Learning
 <br> **Subject:** Mathematics for Machine Learning
 <br> **Language:** Python

> **Description:**  Eigenvalues of a matrix are obtained by solving the characteristic equation
det
⁡
(
𝐴
−
𝜆
𝐼
)
=
0
det(A−λI)=0.
Eigenvectors are the non-zero vectors that satisfy
(
𝐴
−
𝜆
𝐼
)
𝑥
=
0
(A−λI)x=0 for each eigenvalue.
For a 3×3 matrix, a program computes the eigenvalues first and then determines the corresponding eigenvectors using linear equations.

> **Resource:**
  
---
<center> </center>


In [ ]:
import numpy as np

# Function to compute eigenvalues and eigenvectors of 3x3 matrix
def eigen_3x3(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

# ----------- Example Matrix ------------
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])

values, vectors = eigen_3x3(A)

print("Matrix A:")
print(A)

print("\nEigenvalues:")
print(values)

print("\nEigenvectors (each column is an eigenvector):")
print(vectors)

Matrix A:
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]

Eigenvalues:
[3.41421356 2.         0.58578644]

Eigenvectors (each column is an eigenvector):
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  4.05405432e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]
